### ISSUE TITLE
Error in the paths for ckeditor and startup.js

### ISSUE THREAD

**Issue by dactivo** [rixbeck/bolt-extension-editable#11]
The path that the browser looks for is:
http://extensions/vendor/bolt/editable/assets//ckeditor/startup.js

The problem is that two slashes are present at the beginning of the paths.

I have patched it changing the line 119 of ExtensionHelper:
$this->app['extensions']->$addResource(str_replace("//","/",$relpath) . '/' . $filename, $late, $priority);

**Comment by rixbeck** [comment]
Thanks! Patch applied here too...
