### ISSUE TITLE
mediaembed

### ISSUE THREAD

**Issue by Propaganistas** [rixbeck/bolt-extension-editable#3]
Hi

Sorry to interrupt you once again.
It seems the `mediaembed` option isn't working properly?
Can you take a look at this as well?

Thanks.

**Comment by rixbeck** [comment]
Repaired. Thank you!

**Comment by Propaganistas** [comment]
Thanks!
Don't forget to update the docs ;)

**Comment by rixbeck** [comment]
Bingo! :+1:
