### ISSUE TITLE
CKEditor.allowedContent not parsed correctly

### ISSUE THREAD

**Issue by Propaganistas** [rixbeck/bolt-extension-editable#4]
Hi

Here's another one:
I've forked my own version of *startup.js* so I can fine-tune Editable's CKEditor (by adding extra parameters in the `CKEDITOR.config` object).

However, for some reason or the other `allowedContent = true` is working properly, but inserting any self-defined tag string won't.
I discovered this when I plugged in Bolt's default wysiwyg allowedContent string (in config.yml) and my FontAwesome icons (`<i> tag`) were being filtered whenparsed by Editable (despite correct allowance of the <i> tag).

Here's the stuff I'm talking about:

    CKEDITOR.config.extraPlugins = 'editable';
    // Extra parameters
    CKEDITOR.config.autoParagraph = false;
    CKEDITOR.config.allowedContent = true;

vs

    CKEDITOR.config.extraPlugins = 'editable';
    // Extra parameters
    CKEDITOR.config.autoParagraph = false;
    CKEDITOR.config.allowedContent = 'p i(*); strong em strike cite blockquote code ul ol li dl dt dd br h2 h3 h4 h5 h6;a[!href,title];img[!src,width,height,alt,title]{width,height,text-align,float};table thead tbody tr th td[*]{*}(*)';

Thanks for the great support!

**Comment by rixbeck** [comment]
Is it means would your snippet improve the extension? If so would you like to make a pull request to be included? :-)

**Comment by Propaganistas** [comment]
No, I'm reporting that CKEditor's `allowedContent` option parameter isn't working properly in Editable.

**Comment by rixbeck** [comment]
Thank you. Then updated now.

**Comment by Propaganistas** [comment]
I think you misunderstood me. I'm reporting that the `allowedContent` parameter is not working as expected for `<i>` tags in Editable.
However, as a workaround I managed to use `<span>` tags instead of `<i>`.

**Comment by rixbeck** [comment]
As I remember in CKEditor you can just enter tags which are enabled by corresponding toolbar or plugin, additional that are in `allowedContent` option. Although I thought that your snippet is a workaround for this, but I think if `<i>` tags can't be managed in Editable then it isn't an extension related issue but a problem in CKEditor. I would be curious how it is managed in Bolt backend's content editing. Do you agree with? Or what option do you suggest we better to use in Editable?
I must confess I'm not a great fan of CKEditor so I didn't dig in details of its configuration...
