### ISSUE TITLE
Error during install - ::$config must be public

### ISSUE THREAD

**Issue by dizarter** [rixbeck/bolt-extension-editable#9]
ErrorException thrown with message "Access level to Bolt\Extension\Bolt\Editable ExtensionHelper::$config must be public (as in class Bolt\BaseExtension)"
Stacktrace: #0  in ..\extensions\vendor\bolt\editable\src\ExtensionHelper.php:145

I experienced the above error during installation. (Bolt 2.2.11)

Seems fixed by making $config public.

**Comment by rixbeck** [comment]
I'm gonna fix it ASAP. Thanks!
